package FrontEnd;


/**
* FrontEnd/FrontEndInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Wednesday, November 21, 2018 12:45:19 PM EST
*/

public interface FrontEndInterfaceOperations 
{
  String createMRecord (String managerID, String firstName, String lastName, String employeeID, String mailID, FrontEnd.Project[] projects, String location);
  String createERecord (String managerID, String firstName, String lastName, String employeeID, String mailID, String projectID);
  String getRecordCount (String managerID);
  String editRecord (String managerID, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteCenterServerName);
  void shutdown ();
} // interface FrontEndInterfaceOperations
