package FrontEnd;


/**
* FrontEnd/ProjectsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DEMS.idl
* Wednesday, November 21, 2018 12:45:18 PM EST
*/

abstract public class ProjectsHelper
{
  private static String  _id = "IDL:FrontEnd/Projects:1.0";

  public static void insert (org.omg.CORBA.Any a, FrontEnd.Project[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FrontEnd.Project[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = FrontEnd.ProjectHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (FrontEnd.ProjectsHelper.id (), "Projects", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FrontEnd.Project[] read (org.omg.CORBA.portable.InputStream istream)
  {
    FrontEnd.Project value[] = null;
    int _len0 = istream.read_long ();
    value = new FrontEnd.Project[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = FrontEnd.ProjectHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FrontEnd.Project[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      FrontEnd.ProjectHelper.write (ostream, value[_i0]);
  }

}
