package DataStructures;


/**
* DEMSInterface/Project.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Friday, October 26, 2018 6:11:58 o'clock PM EDT
*/

public final class Project
{
    String projectID;
    String projectClient;
    String projectName;
    
    public Project(){
        projectID = "";
        projectClient = "";
        projectName = "";
    }
    
    public Project(String projectID, String projectClient, String projectName){
        if (projectID.matches("[A-Z][0-9]+") && projectID.length() == 6)
            this.projectID = projectID;
        this.projectClient = projectClient;
        this.projectName = projectName;
    }
    
    //Setters
    public void setProjectID(String newID){
        if (newID.matches("[A-Z][0-9]+") && newID.length() == 6)
            projectID = newID;
    }
    
    public void setProjectClient(String newClient){
        projectClient = newClient;
    }
    
    public void setProjectName(String newName){
        projectName = newName;
    }
    
    //Getters
    public String getProjectID(){
        return projectID;
    }
    
    public String getProjectClient(){
        return projectClient;
    }
    
    public String getProjectName(){
        return projectName;
    }
    
    public String toString() {
        return projectID + ", " + projectClient + ", " + projectName;
    }
    @Override
    public boolean equals(Object otherObject){
        if (otherObject == null)
            return false;
        else if (otherObject.getClass() != this.getClass())
            return false;
        else {
            Project project = (Project) otherObject;
            return (this.projectID.equals(project.getProjectID()) && this.projectClient.equals(project.getProjectClient())
                    && this.projectName.equals(project.getProjectName()));
        }
    }
} // class Project
